---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default

---

apiVersion: batch/v1
kind: Job
metadata:
  name: submit
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: gcr.io/spark-operator/spark:v2.4.5
        command: [ "/opt/spark/bin/spark-submit" ]
        args: [ "--master", "k8s://https://kubernetes.default", 
                "--deploy-mode", "cluster",
                "--name", "spark-pi",
                "--class", "org.apache.spark.examples.SparkPi",
                "--conf", "spark.executor.instances=2",
                "--conf", "spark.kubernetes.namespace=default",
                "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark",
                "--conf", "spark.kubernetes.node.selector.*",
                "--conf", "spark.kubernetes.container.image=gcr.io/spark-operator/spark:v2.4.5",
                #"--conf", "spark.kubernetes.executor.volumes.persistentVolumeClaim.checkpointpvc.options.claimName=spark-pvc-claim",
                #"--conf", "spark.kubernetes.executor.volumes.persistentVolumeClaim.checkpointpvc.mount.path=/checkpoint.",
                "--conf", "spark.kubernetes.volumes.emptyDir.spark-shared.mount.path=/tmp",
                "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5.jar" ]
