---

apiVersion: v1
kind: Namespace
metadata:
  name: spark-submit

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-submit
  namespace: spark-submit

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-submit-clusterrole
  namespace: spart-submit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spark-submit
    namespace: spark-submit

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-submit
  name: spark-submit-pod-creator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "watch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-submit-pod-creator
  namespace: spark-submit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-submit
subjects:
  - kind: ServiceAccount
    name: spark-submit
